version: '3.6'

services:
    mysql:
        image: mysql
        restart: always
        container_name: srvtests-db
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./src/main/resources/db:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: springbootsoapws
        networks:
            srvtest_net:
          
    soapwsapp:
        container_name: srvtests-app
        restart: unless-stopped
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springbootsoapws?useSSL=false
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=springbootsoapws
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - mysql
        networks:
            srvtest_net:
        
volumes:
  mysql-data:
    name: test-mysql-data

networks:
    srvtest_net:
        driver: bridge